# Generated by Django 4.2.5 on 2023-10-28 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_feastfortress', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
